# MODULARIZAÇÃO 
# -> É O ATO DE CONTRUIR MÓDULOS, ISTO É, DIVIDIR UM PROGRAMA EM VÁRIOS PEDAÇOS 

# PARA UM MELHOR ENTENDIMENTO, OS EXEMPLOS ESTRÃO DISPONÍVEIS NA PASTA "MODULOS"

def fatorial(n): 
    f = 1 
    for c in range(1, n+1): 
        f *= c 
    return f 

# AGORA, IMAGINE QUE EU TENHA DIVERSAS FUNÇÕES, O CÓDIGO FICARIA IMENSO. PARA ISSO, É POSSÍVEL DIVIDIR O CÓDIGO EM "PEDAÇOS" (MÓDULOS) E MELHORAR A ORGANIZAÇÃO. 

# VANTAGENS DA MODULARIZAÇÃO: 
# ORGANIZAÇÃO DO CÓDIGO; 
# FACILIDADE DE MANUTENÇÃO 
# OCULTAÇÃO DE CÓDIGO DETALHADO 
# REUTILIZAÇÃO DOS MÓDULOS EM OUTROS PROJETOS 